version: '3'
volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
  kafka-1-secret:
  kafka-2-secret:
  kafka-3-secret:

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19092,kafka-2:19093,kafka-3:19094
      DYNAMIC_CONFIG_ENABLED: 'true'

  kafka-1:
    image: confluentinc/cp-kafka:7.5.3
    environment:
      CLUSTER_ID: 2tznpsS6SOG0LgAANBeE7Q
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-1:19092,CONTROLLER://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29093,3@kafka-3:29094
    ports:
      - 9092:9092
    expose:
      - 9092
    volumes:
      - kafka-1-data:/var/lib/kafka/data
      - kafka-1-secret:/etc/kafka/secrets

  kafka-2:
    image: confluentinc/cp-kafka:7.5.3
    environment:
      CLUSTER_ID: 2tznpsS6SOG0LgAANBeE7Q
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-2:19093,CONTROLLER://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://localhost:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29093,3@kafka-3:29094
    ports:
      - 9093:9093
    expose:
      - 9093
    volumes:
      - kafka-2-data:/var/lib/kafka/data
      - kafka-2-secret:/etc/kafka/secrets

  kafka-3:
    image: confluentinc/cp-kafka:7.5.3
    environment:
      CLUSTER_ID: 2tznpsS6SOG0LgAANBeE7Q
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka-3:19094,CONTROLLER://kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29093,3@kafka-3:29094
    ports:
      - 9094:9094
    expose:
      - 9094
    volumes:
      - kafka-3-data:/var/lib/kafka/data
      - kafka-3-secret:/etc/kafka/secrets

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nest-kafka:dev
    environment:
      - NODE_ENV=development
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - 3000:3000
